### ISSUE TITLE
My Favorites  - Spelling mistake and lines not complete from left to right

### ISSUE THREAD

**Issue by diva6504** [sriks/history_ios#7]
Change the spelling 
Expected: My Favourites

horizontal lines shown in this section which divides the favourites should be complete.(left to right)or make it center.
there is a space at left side of line.

**Comment by sriks** [comment]
Since the app focuses on American history using "favorites" (American English).
See http://grammarist.com/spelling/favorite-favourite/

PS: One issue should hold only one bug.
